### ISSUE TITLE
Revkit Installation

### ISSUE THREAD

**Issue by Saranya-Nkl** [msoeken/cirkit#1]
Hello Sir,
I have installed the Revkit tool using the steps given in README file. I wish to draw a Quantum circuit (using BDD synthesis). But i couldn't find any executable file in revkit_viewer(which is in the build directory within gui)
![gui folder](https://cloud.githubusercontent.com/assets/18566268/14669793/14917480-0708-11e6-9d60-82a1652e0101.png)
. I herewith attached the image which i have done so far. Kindly sort out the problem.
![screenshot from 2016-04-20 14 25 49](https://cloud.githubusercontent.com/assets/18566268/14669556/11a1efda-0707-11e6-8f3b-c4b2c3e864b3.png)

**Comment by msoeken** [comment]
`revkit_viewer` does not support good support to view quantum circuits. There is the command  “write_quipper -c <filename>” in the RevKit github version that writes Quipper files. These can be processed with Quipper to decompose them into quantum circuits and display them.
