### ISSUE TITLE
Small typo in README.md

### ISSUE THREAD

**Issue by Atanahel** [msoeken/cirkit#11]
Just to point out that you probably wanted to write : 
`export PATH=<path-to-cirkit>/ext/bin:$PATH`
instead of 
`export PATH=<path-to-cirkit>/ext/bin:PATH`

Because some people like me are lazy and don't look at what I'm copying and pasting...
Cheers

**Comment by msoeken** [comment]
Thanks, I fixed the problem in 984a6c6
