### ISSUE TITLE
ESOP based Synthesis

### ISSUE THREAD

**Issue by HariMohan84** [msoeken/cirkit#16]
Hi 

I am facing two small issues regarding revkit

**1)** What is the procedure for ESOP based synthesis??
for example 
In case of tbs we have to perform
pla to bdd 
bdd to rbdd
tbs
what we do for esopbs???
please share any sample program (*.cs file or list of instructions) for esopbs.

**2)** Another issue is regarding creating truth table from circuit.
The command "circuit > spec" not performing and at the output, it is written "unknown command: circuit". The error is occurring also in the example 4 (create random circuit) of demo.cs

Please solve the issues.

**Comment by choforito84** [comment]
Regarding error 2), I would recommend not to use the alias `circuit > spec` and instead call the complete command  `convert --circuit_to_spec`.

**Comment by msoeken** [comment]
1) The best for esop based synthesis is to start with an AIG

Examples:

    read_aiger file.aig
    esopbs -ae
    ps -c

or

    tt 0xcafe
    tt > aig
    esopbs -ae
    ps -c

2) As pointed out by choforito84 in the other comment, you can use the `convert` command directly. The best is to use the aliases instead. Just set the `$CIRKIT_HOME` environment variable to the path where CirKit is, as described in [here](https://msoeken.github.io/cirkit_doc.html#getting-started-aliases)

Please note that in this scientific open source project I have no obligation to maintenance.
