### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by AliRady** [msoeken/cirkit#29]
While making I get the following error: 

![screenshot from 2017-04-01 17-03-03](https://cloud.githubusercontent.com/assets/26838955/24579392/3af5ad16-16fd-11e7-849b-10519869d5f5.png)

This is at the "make external' step. I have cmake and git built and updated.

**Comment by msoeken** [comment]
Can you please attach the abc-build-*.log file that is mentioned in the output.

**Comment by AliRady** [comment]
The files that match that name format in that directory are as follows: 

[abc-build-err.txt](https://github.com/msoeken/cirkit/files/887694/abc-build-err.txt)
[abc-build-out.txt](https://github.com/msoeken/cirkit/files/887695/abc-build-out.txt)

Their file type was .log but I changed it to .txt so it can be uploaded here.

**Comment by msoeken** [comment]
The abc-build-err.txt file indicates that it was an internal compiler error. This bug is hard to trace. The problem may be solved by changing the compiler. Could you try with `clang`?

**Comment by AliRady** [comment]
Problem resolved, my Linux wasn't updating properly. Thank you.

**Comment by msoeken** [comment]
Great, thanks for letting me know.
