### ISSUE TITLE
Error converting negative control gates

### ISSUE THREAD

**Issue by choforito84** [msoeken/cirkit#32]
I've been trying to convert a simple .real file to a .spec using read_real, convert --circuit_to_spec and write_spec. The circuit consists of only one negative control  Fredkin gate (size 3). The . real file is the following
```
# Function: Fredkin gate
# Used Library: MCT (gates: 1, quantum costs: 7)
# This file have been taken from RevLib (www.revlib.org).
.version 1.0
.numvars 3
.variables a b c
.inputs a b c
.outputs a b c
.constants ---
.garbage ---
.begin
f3 -c a b
.end
```

When I run 'convert --circuit_to_spec', the program lauches the following error code and exits revkit.
```
revkit: /cirkit/addons/cirkit-addon-reversible/src/reversible/simulation/simple_simulation.cpp:65: boost::dynamic_bitset<>& cirkit::core_gate_simulation::operator()(const cirkit::gate&, boost::dynamic_bitset<>&) const: Assertion `v.polarity()' failed.
Aborted (core dumped)

```

I assumed that, as RevKit does not show any warning when reading the file and can print the circuit in the console line, that it supported negative controls for this kind of gates, but it can not simply simulate it.

Is there a way to achieve this conversion to a .spec file?

**Comment by msoeken** [comment]
The simple simulation algorithm does not support negative control lines for Fredkin gates at the moment. Without a modification of the source code you can do the following

    pos
    tof
    convert --circuit_to_spec

`pos` makes negative control lines positive by adding NOT gates, and `tof` translates Fredkin gates into Toffoli gates.

**Comment by choforito84** [comment]
That solved my problem. Thank you very much!
