### ISSUE TITLE
Problem using ipython while importing revkit module

### ISSUE THREAD

**Issue by pulkit561** [msoeken/cirkit#35]
I have installed revkit v1.3 with all its dependencies and my aim is to write a code in ipython. But while importing revkit module in the very first line in ipython3 it shows an error shown in the attached image.

![screenshot from 2017-07-11 11-25-35](https://user-images.githubusercontent.com/19650293/28053054-15c2c546-662c-11e7-90a5-d658296af6a8.png)

I also want to know if this still doesnt work, is there any other approach I can try and can review what built-in methods are available in revkit as it will help me in writing my code.
Thanks!

**Comment by msoeken** [comment]
Support for RevKit 1.3 is long discontinued. Please check the github version. You can compile a Python library by enabling the `cirkit_ENABLE_PYTHON_API` in `cmake`.
