### ISSUE TITLE
Python interface not loading

### ISSUE THREAD

**Issue by choforito84** [msoeken/cirkit#44]
I can't use Revkit's Python API. When I try to import the package with `import revkit`, I get the `ImportError: No module named revkit` error. I have tried to do this from Python 3.5.2 and Python 2.7.12, and I get the same error in both distributions. 

As the [Jupyter Notebook demonstration states](https://github.com/msoeken/cirkit/blob/master/jupyter/LHRS.ipynb), I have set the `PYTHONPATH`environment variable to $CIRKIT_HOME/build/programs.

I attach a screenshot of my terminal and executions for more clarity.

![pythoninterface1](https://user-images.githubusercontent.com/20233700/29291128-c4398572-80ff-11e7-8908-34197200dfb9.png)

**Comment by choforito84** [comment]
I have installed `pybind11` and ran the complete command of `cmake`. `make revkit_python` runs, but I get an error at the end of the compilation with a function called `PyUnicode_AsUTF8`. I attach the screenshot.

![pythoninterface2](https://user-images.githubusercontent.com/20233700/29339620-4fa76fd8-81d8-11e7-83db-b07b295ca515.png)

**Comment by choforito84** [comment]
![pythoninterface3](https://user-images.githubusercontent.com/20233700/29339658-72c37caa-81d8-11e7-81a5-35e47ef94f61.png)

**Comment by msoeken** [comment]
It seems that there are mismatches with the Python versions, but this should be fixed on my side. I think I need to use pybind11 functions instead of plain CPython API calls in alice.hpp. I will look into it soon to get it fixed.

**Comment by choforito84** [comment]
Thank you very much!

**Comment by msoeken** [comment]
I have changed this code a while ago and the code that caused problems has been replaced. I am closing this bug for now.
