### ISSUE TITLE
Is it possible to choose specific library to synthesize a circuit?

### ISSUE THREAD

**Issue by fever2052** [msoeken/cirkit#49]
Hello Mathias,

I was wondering if it is possible to choose a specific gate library to synthesize a circuit with it. For instance 
for this circuit 
`read_spec -p "0 1 2 3 4 5 6 15 8 9 10 11 12 13 14 7"`
which respond to a multi control Toffoli (3 control lines). How can I synthesize this simple circuit using just NCT using Revkit?

Thanks

**Comment by msoeken** [comment]
Hello,

you mean NCT as in NOT, CNOT, and 2-controlled Toffoli gate? Then use, e.g., `tbs` or `rms`, or `dbs` to get a MCT network, then use `pos` to change all negative controls into positive ones, if there are any, and then use `nct` to decompose large Toffoli gates into smaller ones. You could try `revsimp` afterwards for some post-optimization, but this may lead again to larger gates and negative controls.

Best,
Mathias
