### ISSUE TITLE
How to limit the MCT gates control signals

### ISSUE THREAD

**Issue by fever2052** [msoeken/cirkit#50]
Hi Mathias,

I was wondering if there is a tool on RevKit that can limit the number the synthesis of a circuit to a certain number of control signals via MCT gates. For instance if in a circuit after synthesizing by default, we have MCT gates with 10 control lines. But We want that control signals of all MCT gates don't exceed 5 control signals. Is it possible to do so using RevKit?

In other words, we want to break down the 10 control signal toffoli and substitute it with its 5 control signals MCT gates. 

I also wanted to thank you for your time on answering my posts. Thanks for your great support on the software.

**Comment by msoeken** [comment]
Hi,

Yes, there is a way. You can call `nct -t 5`. This will stop decomposition for large gates once you reach gates with 5 control lines. You can make this number large to keep larger gates. Gates in your circuit that are below this threshold will not be decomposed.

Glad I can help and hope that RevKit is useful for you.

Best,
Mathias
