### ISSUE TITLE
How to ignore don't cares when synthesizing a truth table.

### ISSUE THREAD

**Issue by fever2052** [msoeken/cirkit#52]
Hi Mathias,

I have another question about the Revkit. Is there any possibility that I would be able to synthesize a given truth table using read_spec or any other read input command to give a truth table to the Revkit while some of the inputs / outputs are don't cares. For say I want to synthesize a truth table with 4 bits input and output using TBS technique which 8 of the inputs/outputs won't happen in my case so they are don't cares.  

Thanks.

**Comment by msoeken** [comment]
Hi Sajad,

At the moment, you can only use exact synthesis for this, so it will work for small functions, but 4 inputs should work fine. Assume you have a SPEC file `test.spec` with don't cares, for example:

```
.numvars 3
.begin
001
010
100
---
---
---
---
---
.end
```

Then you can run:

```
revkit> read_spec test.spec
revkit> exs
```

This gives you a circuit that will fill the don't cares such that a minimum circuit is obtained. You can verify the result:

```
revkit> convert --circuit_to_spec
revkit> print -s
```

and see that you now have a complete spec, but the original entries are kept.

There is some code to embed incomplete truth tables before synthesis, but I have not yet exposed them to the CLI using a command. I might do that. Then the flow would be to read an incomplete SPEC, embed it, and then use any of the other approaches for example `tbs`, `dbs`, or `rms`.

Best,
Mathias

**Comment by fever2052** [comment]
Aha, That's great. Thanks for the response
