### ISSUE TITLE
make revkit命令出错

### ISSUE THREAD

**Issue by WuYu-99** [msoeken/cirkit#69]
Dear Professor Mathias Soeken，
        I have the following problem when installing revkit：
      https://cirkit.readthedocs.io/en/latest/installation.html
Follow this link to install, when I input “ make revkit”, the following error occurs
 
![image](https://user-images.githubusercontent.com/44435066/54524164-32620d00-49ac-11e9-85aa-794309b96bec.png)

**Comment by msoeken** [comment]
Hello, which distribution and which compiler are you using to compile RevKit? Could you please send the full build log, dumped as text, not as a screenshot.

**Comment by WuYu-99** [comment]
Dear Professor Mathias Soeken，
  Linux ubuntu 16.04
   gcc 8.2.0
 
[CMakeError.log](https://github.com/msoeken/cirkit/files/2978015/CMakeError.log)
Thank you very much!

**Comment by msoeken** [comment]
Could you also send the complete output from `make revkit`.

**Comment by WuYu-99** [comment]
Thank you!
This is  the complete output from make revkit.
[output.txt](https://github.com/msoeken/cirkit/files/2978126/output.txt)

**Comment by msoeken** [comment]
The output seems incomplete. Could you please run the following command and send `output.txt`:

```
make revkit 2>&1 > output.txt
```

**Comment by WuYu-99** [comment]
[output.txt](https://github.com/msoeken/cirkit/files/2981012/output.txt)
Thank you very much, Professor!

**Comment by WuYu-99** [comment]
[output.txt](https://github.com/msoeken/cirkit/files/2981056/output.txt)
Thank you very much!

**Comment by WuYu-99** [comment]
Dear Professor Mathias Soeken，
My problem has not been solved yet. Can you help me?
Best Wish!

**Comment by msoeken** [comment]
Hi, thanks for sending the updated log. I see that you are using RevKit 2.x. I suggest to use the newer version, depending on what functionality you are using. The older versions are no longer maintained. It seems that the error is coming from the interaction with xtensor.
