### ISSUE TITLE
sudo python3 setup.py install getting stuck for hours.

### ISSUE THREAD

**Issue by gari0894** [msoeken/cirkit#70]
Hello sir,
I am trying to install python libraries in dist/cirkit but the installation is getting stuck for hours . However the installation worked fine with dist/revkit. Can you please help me with this problem. 
Looking forward to your response. 
Below is the screenshot of the same.
![image](https://user-images.githubusercontent.com/48807996/54871566-157a6f00-4ddc-11e9-90f1-ea544fc317bd.png)

Thanks

**Comment by msoeken** [comment]
The screenshot is only showing a warning. This will not cause the error.

Please send the error and output log (as text file, not screenshot) of the compile command, the operating system and the compiler you are using.

**Comment by gari0894** [comment]
Hi,
I am attaching the log of the sudo python3 setup.py install command . The command execution is getting hung and not getting completed for neither revkit nor cirkit. Please help me out with this issue sir. 
[log.txt](https://github.com/msoeken/cirkit/files/3000536/log.txt)

Thanks.
