### ISSUE TITLE
error in make revkit. 

### ISSUE THREAD

**Issue by gari0894** [msoeken/cirkit#76]
Hi Sir,
I am trying to download the cirkit and revkit 2.0 from the develop branch but i am getting the following error for make revkit.
Please help me out with this . 

Thanks and Regards,
Garima. 
![Screenshot from 2019-06-05 16-57-58](https://user-images.githubusercontent.com/48807996/58953119-2ae42000-87b3-11e9-8cbb-6b3101f04d2a.png)

**Comment by msoeken** [comment]
Dear Garima, unfortunately RevKit 2.0 is no longer maintained. Best, Mathias
